### ISSUE TITLE
The problem of g.clear(context) in concurrent requests

### ISSUE THREAD

**Issue by heysaeid** [chrisK824/fastapi-g-context#2]
When two requests are sent concurrently, an AttributeError occurs due to g.clear(context).
```python
async def set_globals():
    g.username = "JohnDoe"

@app.get("/set_globals1", dependencies=[Depends(set_globals)])
async def set_globals_endpoint_1():
    print(g.username)
    await asyncio.sleep(2)
    print(g.username)

@app.get("/set_globals2")
async def set_globals_endpoint_2():
    await asyncio.sleep(5)
```

```shell
...
raise AttributeError(
AttributeError: 'username' variable does not exist in globals, make sure to set it before trying to use it
```

**Comment by chrisK824** [comment]
Hey there, thanks for the feedback. I am currently ill tbh so I will try to attack this as soon I feel a bit better.

May I ask how did you perform your concurrent requests so that I can replicate it fairly easily?

**Comment by heysaeid** [comment]
Hope you feel better soon! Yeah, you can try this way:
```shell
curl http://localhost:8000/set_globals1 & sleep 1 && curl http://localhost:8000/set_globals2
```

**Comment by chrisK824** [comment]
Hey @heysaeid , thanks mate, I feel a bit better now!

I took a look in the issue and pushed a refactored globals class to use a single context variable and adjusted the internal mechanics. I added a test to replicate the issue you saw beforehands, which of course was failing, and it passes just fine with the new implementation.

Please let me know if that seems ok with you too, so we can close this issue, cheers!

**Comment by heysaeid** [comment]
It looks great now, I closed it ✌️🥳
